CREATE PROCEDURE CheckBooking (CHECK_DATE DATE,TABLE_ID INT)
BEGIN
	IF EXISTS (
		SELECT * FROM Bookings
		WHERE TABLEID = TABLE_ID
		AND BOOKINGDATE = CHECK_DATE
	) THEN

		SELECT CONCAT('Table ',TABLE_ID,' is already booked.') as BOOKING_STATUS;

	ELSE 

		SELECT CONCAT('Table ',TABLE_ID,' is open for booking.') as BOOKING_STATUS;

	END IF;
END