/**  SLIGHTLY MODIFIED INPUTS AS BOOKING ID IS AUTO INCREMENTED ON MY DESIGN AND I REQUIRE A FEW EXTRA FIELDS**/
CREATE PROCEDURE UpdateBooking(IN BOOKING_ID INT, IN CHECK_DATE DATE, IN TIMESLOTS TIME, IN CUSTOMER_ID INT,IN N_OfGUESTS INT)
BEGIN 
DECLARE CURRENT_BOOKING_DATE DATE;
DECLARE CURRENT_BOOKING_SLOT TIME;
SET autocommit = 0;
START TRANSACTION;
	SET CURRENT_BOOKING_DATE = (SELECT BookingDate FROM Bookings WHERE 1=1 AND CustomerId = CUSTOMER_ID AND idBookings = BOOKING_ID);
    SET CURRENT_BOOKING_SLOT = (SELECT TimeSlot FROM Bookings WHERE 1=1 AND CustomerId = CUSTOMER_ID AND idBookings = BOOKING_ID);
    
	IF (N_OfGUESTS = 0) THEN
		SET N_OfGUESTS = (SELECT NumberOfGuests FROM Bookings WHERE 1=1 AND CustomerId = CUSTOMER_ID AND idBookings = BOOKING_ID);
    END IF;

	IF (CURRENT_BOOKING_DATE = CHECK_DATE) THEN
		SET CHECK_DATE = CURRENT_BOOKING_DATE;
    END IF;

	IF (CURRENT_BOOKING_SLOT = TIMESLOTS) THEN
		SET TIMESLOTS = CURRENT_BOOKING_SLOT;
    END IF;

	IF NOT EXISTS (
		SELECT * FROM Bookings
		WHERE idBookings = BOOKING_ID
		AND CustomerID = CUSTOMER_ID
	) THEN
		
		ROLLBACK;
		SELECT CONCAT('Booking not valid.') as BOOKING_STATUS;
	ELSE 
		UPDATE Bookings
			SET TimeSlot = TIMESLOTS,
            BookingDate = CHECK_DATE,
            NumberOfGuests = N_OfGUESTS
		WHERE 1=1
			AND CustomerId = CUSTOMER_ID
            AND idBookings = BOOKING_ID;
		COMMIT;
        SELECT CONCAT('Booking has successfully been updated. See you soon!') as BOOKING_STATUS;
	END IF;
 END